config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :people, only: [:show, :new, :create] do
    resources :life_events, except: [:show, :index]
    resources :schools, except: [:show, :index]
  end

  resources :comments, only: [:new, :create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :text, presence: true,
                   length: { maximum: 140 }

  belongs_to :commentable, polymorphic: true
end

app/models/life_event.rb
class LifeEvent < ActiveRecord::Base
  validates :title, presence: true
  validates :year, presence: true
  validates :description, presence: true,
                          length: { maximum: 140 }

  belongs_to :person

  has_many :comments, as: :commentable
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :name, presence: true,
                   uniqueness: true

  has_many :schools
  has_many :life_events
end

app/models/school.rb
class School < ActiveRecord::Base
  validates :name, presence: true
  validates :beginning_year, presence: true,
                             numericality: { less_than_or_equal_to: :ending_year }
  validates :ending_year, presence: true
  validates :person_id, presence: true

  belongs_to :person

  has_many :comments, as: :commentable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @schools = School.all
    @events = LifeEvent.all
    @people = Person.all
    @feed = @schools + @events + @people
  end
end

app/controllers/life_events_controller.rb
class LifeEventsController < ApplicationController
  before_action :set_life_event, only: [:edit, :update, :destroy]

  def new
    @life_event = LifeEvent.new
  end

  def edit
  end

  def create
    @life_event = LifeEvent.new(life_event_params)
    @person = Person.find(params[:person_id])
    @life_event.person = @person

    respond_to do |format|
      if @life_event.save
        format.html { redirect_to person_path(@person), notice: 'Life event was successfully created.' }
        format.json { render :show, status: :created, location: @life_event }
      else
        format.html { render :new }
        format.json { render json: @life_event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @life_event.update(life_event_params)
        format.html { redirect_to @life_event, notice: 'Life event was successfully updated.' }
        format.json { render :show, status: :ok, location: @life_event }
      else
        format.html { render :edit }
        format.json { render json: @life_event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @life_event.destroy
    respond_to do |format|
      format.html { redirect_to life_events_url, notice: 'Life event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_life_event
      @life_event = LifeEvent.find(params[:id])
    end

    def life_event_params
      params.require(:life_event).permit(:title, :year, :description, :person_id)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def new
    @person = Person.new
  end

  def show
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def person_params
    params.require(:person).permit(:name)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:edit, :update, :destroy]

  def new
    @school = School.new
  end

  def edit
  end

  def create
    @school = School.new(school_params)
    @person = Person.find(params[:person_id])
    @school.person = @person

    respond_to do |format|
      if @school.save
        format.html { redirect_to person_path(@person), notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to person_path(@person), notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_school
      @school = School.find(params[:id])
      @person = Person.find(params[:person_id])
      @school.person = @person
    end

    def school_params
      params.require(:school).permit(:name, :beginning_year, :ending_year, :person_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/life_events_helper.rb
module LifeEventsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/home/index.html.erb
<%= content_for :title, 'Home' %>

<div class='row'>
  <div class='columns large-12 text-center'>
    <h1>Welcome to Life Tracker</h1>
  </div>
</div>

<div class='row'>
  <div class='columns large-8 text-center'>
    <div class='row'>
      <div class='columns large-8'>
        <h2><%= fa_icon 'reorder' %>    The Feed</h2>
        <% @feed.sort_by(&:created_at).reverse.each do |feed| %>
          <% if feed.class == School  %>
            <p><%= link_to feed.person.name, person_path(feed.person) %> added <%= feed.name %> on <%= feed.created_at.to_formatted_s(:short) %></p>
          <% elsif feed.class == LifeEvent %>
            <p><%= link_to feed.person.name, person_path(feed.person) %> added <%= feed.title %> on <%= feed.created_at.to_formatted_s(:short) %></p>
          <% else %>
            <p><%= link_to feed.name, person_path(feed) %> was added to Life Tracker on <%= feed.created_at.to_formatted_s(:short) %></p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class='columns large-4 text-center'>
    <h2><%= fa_icon 'group' %>    The People</h2>
    <% @people.each do |person| %>
      <h6><%= link_to person.name, person_path(person) %></h6></br>
    <% end %>
    <h4><%= link_to 'Add Person', new_person_path %></h4>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? "Life Tracker | #{yield(:title)}" : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class='top-bar' data-topbar>
      <ul class='title-area'>
        <li class='name'>
          <h1><%= link_to 'Life Tracker', root_path %></h1>
        </li>
      </ul>
    </nav>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/life_events/_form.html.erb
<div class='columns large-4 large-centered text-center'>
  <%= simple_form_for [@person, @life_event], url: person_life_events_path do |f| %>
    <%= f.input :title %>
    <%= f.input :year %>
    <%= f.input :description %>
    <%= f.button :submit %>
  <% end %>
  <%= link_to 'Go back', root_path %>
</div>

app/views/life_events/edit.html.erb
<h1>Editing life_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @life_event %> |
<%= link_to 'Back', life_events_path %>

app/views/life_events/index.html.erb
<h1>Listing life_events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @life_events.each do |life_event| %>
      <tr>
        <td><%= life_event.person.name %></td>
        <td><%= life_event.title %></td>
        <td><%= life_event.year %></td>
        <td><%= life_event.description %></td>
        <td><%= link_to 'Show', life_event %></td>
        <td><%= link_to 'Edit', edit_life_event_path(life_event) %></td>
        <td><%= link_to 'Destroy', life_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Life event', new_life_event_path %>

app/views/life_events/new.html.erb
<%= content_for :title, 'New Life Event' %>

<h1 class='text-center'>New Life Event</h1>

<%= render 'form' %>

app/views/life_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @life_event.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @life_event.year %>
</p>

<p>
  <strong>Description:</strong>
  <%= @life_event.description %>
</p>

<%= link_to 'Edit', edit_life_event_path(@life_event) %> |
<%= link_to 'Back', life_events_path %>

app/views/people/new.html.erb
<%= content_for :title, 'New Person' %>

<div class='columns large-4 large-centered text-center'>
  <h2>Add a New Person to Life Tracker</h2>
  <%= simple_form_for @person do |f| %>
    <%= f.input :name, placeholder: "Person's Name", label: false %>
    <%= f.button :submit %>
  <% end %>
  <%= link_to 'Go Back', root_path %>
</div>

app/views/people/show.html.erb
<%= content_for :title, @person.name %>

<h1 class='text-center'>The Sweet Life of <%= @person.name %></h2>
<div class='row text-center'>
  <div class='columns large-6'>
    <h2>Schools</h2>
    <% @person.schools.order(:beginning_year).each do |school| %>
      <p><%= school.name %> <%= school.beginning_year %></p>
    <% end %>
    <%= link_to 'Add School', new_person_school_path(@person) %>

  </div>
  <div class='columns large-6'>
    <h2>Life Events</h2>
    <% @person.life_events.order(:year).each do |event| %>
      <p><%= event.title %> <%= event.year %></p>
    <% end %>
    <%= link_to 'Add Life Event', new_person_life_event_path(@person) %>
  </div>
</div>

app/views/schools/_form.html.erb
<div class='columns large-4 large-centered text-center'>
  <%= simple_form_for [@person, @school], url: person_schools_path do |f| %>
    <%= f.input :name %>
    <%= f.input :beginning_year %>
    <%= f.input :ending_year %>
    <%= f.button :submit %>
  <% end %>
  <%= link_to 'Go back', root_path %>
</div>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Beginning year</th>
      <th>Ending year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.person.name %></td>
        <td><%= school.name %></td>
        <td><%= school.beginning_year %></td>
        <td><%= school.ending_year %></td>
        <td><%= link_to 'Show', person_school_path(school.id, school.person_id) %></td>
        <td><%= link_to 'Edit', edit_person_school_path(school.id, school.person_id) %></td>
        <td><%= link_to 'Destroy', person_school_path(school.id, school.person_id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_person_school_path %>

app/views/schools/new.html.erb
<%= content_for :title, 'New School' %>

<h1 class='text-center'>New School</h1>

<%= render 'form' %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Beginning year:</strong>
  <%= @school.beginning_year %>
</p>

<p>
  <strong>Ending year:</strong>
  <%= @school.ending_year %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>